
def max_number(a, b):
    try:
        return max(a, b)
    except Exception as ex:
        print(f'Error information: {ex}')

res = max_number(3, 6)
print(res

